### ISSUE TITLE
CI can't find tmpdir

### ISSUE THREAD

**Issue by logicminds** [puppetlabs/pdk-docker#30] opened 2021-04-05 15:27 UTC
## Describe the Bug
When running under the CI system,  the pdk validate command fails because it cannot find a temp directory

## Expected Behavior
pdk validate and other commands would run and complete without error

The image would have everything needed to run this in a CI
## Steps to Reproduce
1. Have pdk module
2. Use gitlab ci
3. use the following or similar ci file that utilizes the docker image

```
---
stages:
  - syntax
  - unit
  - deploy

variables:
  # None of these seem to work
  TMPDIR: '/tmp'
  TMP: '/tmp'
  TEMP: '/tmp'
image: 
  name: puppet/pdk
  entrypoint: [""]


default:
  cache:
    paths:
      - vendor/bundle

validate_6:
  stage: syntax
  script:
    - pdk validate
  variables:
    PDK_PUPPET_VERSION: '6'

test_6:
  stage: unit
  script:
    - pdk test unit
  variables:
    PDK_PUPPET_VERSION: '6'

validate_7:
  stage: syntax
  script:
    - pdk validate
  variables:
    PDK_PUPPET_VERSION: '7'

test_7:
  stage: unit
  script:
    - pdk test unit
  variables:
    PDK_PUPPET_VERSION: '7'
```

## Environment
PDK 2.x

## Additional Context
```
$ pdk validate
pdk (INFO): Using Ruby 2.5.8
pdk (INFO): Using Puppet 6.21.1
pdk (INFO): Running all available validators...
/opt/puppetlabs/pdk/private/ruby/2.4.10/lib/ruby/2.4.0/tmpdir.rb:35:in `tmpdir': could not find a temporary directory (ArgumentError)
	from /opt/puppetlabs/pdk/private/ruby/2.4.10/lib/ruby/2.4.0/tmpdir.rb:112:in `tmpdir'
	from /opt/puppetlabs/pdk/private/ruby/2.4.10/lib/ruby/2.4.0/tmpdir.rb:134:in `create'
	from /opt/puppetlabs/pdk/private/ruby/2.4.10/lib/ruby/2.4.0/tempfile.rb:131:in `initialize'
	from /opt/puppetlabs/pdk/private/ruby/2.4.10/lib/ruby/gems/2.4.0/gems/pdk-2.0.0/lib/pdk/cli/exec/command.rb:32:in `new'
	from /opt/puppetlabs/pdk/private/ruby/2.4.10/lib/ruby/gems/2.4.0/gems/pdk-2.0.0/lib/pdk/cli/exec/command.rb:32:in `initialize'
	from /opt/puppetlabs/pdk/private/ruby/2.4.10/lib/ruby/gems/2.4.0/gems/pdk-2.0.0/lib/pdk/util/bundler.rb:252:in `new'
	from /opt/puppetlabs/pdk/private/ruby/2.4.10/lib/ruby/gems/2.4.0/gems/pdk-2.0.0/lib/pdk/util/bundler.rb:252:in `bundle_command'
	from /opt/puppetlabs/pdk/private/ruby/2.4.10/lib/ruby/gems/2.4.0/gems/pdk-2.0.0/lib/pdk/util/bundler.rb:100:in `installed?'
	from /opt/puppetlabs/pdk/private/ruby/2.4.10/lib/ruby/gems/2.4.0/gems/pdk-2.0.0/lib/pdk/util/bundler.rb:37:in `ensure_bundle!'
	from /opt/puppetlabs/pdk/private/ruby/2.4.10/lib/ruby/gems/2.4.0/gems/pdk-2.0.0/lib/pdk/cli/validate.rb:105:in `block (2 levels) in <module:CLI>'
	from /opt/puppetlabs/pdk/private/ruby/2.4.10/lib/ruby/gems/2.4.0/gems/cri-2.10.1/lib/cri/command.rb:329:in `run_this'
	from /opt/puppetlabs/pdk/private/ruby/2.4.10/lib/ruby/gems/2.4.0/gems/cri-2.10.1/lib/cri/command.rb:269:in `run'
	from /opt/puppetlabs/pdk/private/ruby/2.4.10/lib/ruby/gems/2.4.0/gems/cri-2.10.1/lib/cri/command.rb:287:in `run'
	from /opt/puppetlabs/pdk/private/ruby/2.4.10/lib/ruby/gems/2.4.0/gems/pdk-2.0.0/lib/pdk/cli.rb:71:in `run'
	from /opt/puppetlabs/pdk/private/ruby/2.4.10/lib/ruby/gems/2.4.0/gems/pdk-2.0.0/exe/pdk:6:in `<top (required)>'
	from /opt/puppetlabs/pdk/private/ruby/2.4.10/bin/pdk:23:in `load'
	from /opt/puppetlabs/pdk/private/ruby/2.4.10/bin/pdk:23:in `<main>'
Cleaning up file based variables
```

**Comment by sanfrancrisko** [comment] 2021-05-17 10:35
@logicminds , if you specify the `builds_dir` and `cache_dir` to be `/tmp` like this [example](https://github.com/voxpupuli/puppet-gitlab_ci_runner#usage) does it work?

Having said that, I see Gitlab are advising against using `/tmp` for the `builds_dir` directory: https://gitlab.com/gitlab-org/gitlab-runner/-/issues/25799

**Comment by logicminds** [comment] 2021-05-17 17:25
Well the problem is with pdk running in a container on a CI and not gitlab.  Which since the container is started without a interactive tty I bet the basic environment variables are not set. Additionally, maybe have something to do with me overriding the entrypoint.  The container running doesn't have the temp environment set so I am thinking that I either set that in the CI config or  set in the PDK dockerfile so it is hard coded.  

`/opt/puppetlabs/pdk/private/ruby/2.4.10/lib/ruby/2.4.0/tmpdir.rb:35:in `tmpdir': could not find a temporary directory (ArgumentError)`

Is anyone else running into this issue?  Seems silly to not use pdk in the CI pipeline.

**Comment by sanfrancrisko** [comment] 2021-06-28 08:55
@logicminds I'm able to get the PDK Docker container to work on a Github Workflow (see [here](https://github.com/puppetlabs/puppetlabs-testing/pull/375)). I've not tried any other CIs, but, I think the way Gitlab handles those ENV vars this is likely a factor.

You mentioned you've overridden the entry point to the container. What is it that you've done?

**Comment by cdenneen** [comment] 2021-08-19 10:46
@logicminds why are you setting tmpdir? I use pdk image in gitlab without problem.

**Comment by da-ar** [comment] 2021-09-20 08:54
Closing this issue as we have been unable to reproduce and there has been no further responses.

**Closed by da-ar** 2021-09-20 08:54 UTC
Labels: bug
